name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      if: github.event_name == 'push'
    - name: Publish
      run: dotnet publish --configuration Release
    # - name: Rewrite base href
    # You may pin to the exact commit or the version.
    # uses: SteveSandersonMS/ghaction-rewrite-base-href@5b54862a8831e012d4f1a8b2660894415fdde8ec
    # uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
    # with:
        # Path to the HTML file to be updated
        # html_path: WebSudoku/Client/bin/Release/net6.0/publish/wwwroot/index.html
        # New base href to be applied
        # base_href: WebSudoku
    - name: Move files
      run: |
        mkdir ./public
        mv apb97.github.io/Client/bin/Release/net6.0/publish/wwwroot ./public
        mv apb97.github.io/Client/404.html ./public/wwwroot
    - name: GitHub Pages action
    # You may pin to the exact commit or the version.
    # uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
      # Set a SSH private key from repository secret value for pushing to the remote branch.
      # deploy_key: # optional
      # Set a generated GITHUB_TOKEN for pushing to the remote branch.
        github_token: ${{ secrets.GITHUB_TOKEN }} # optional
      # Set a personal access token for pushing to the remote branch.
      # personal_token: # optional
      # Set a target branch for deployment.
      # publish_branch: # optional, default is gh-pages
      # Set an input directory for deployment.
        publish_dir: public/wwwroot # optional, default is public
      # Set an destination subdirectory for deployment.
      # destination_dir: # optional, default is 
      # Set an external repository (owner/repo).
      # external_repository: # optional
      # If empty commits should be made to the publication branch
      # allow_empty_commit: # optional, default is false
      # If existing files in the publish branch should be not removed before deploying
      # keep_files: # optional, default is false
      # Keep only the latest commit on a GitHub Pages branch
      # force_orphan: # optional, default is false
      # Set Git user.name
      # user_name: # optional
      # Set Git user.email
      # user_email: # optional
      # Set a custom commit message with a triggered commit hash
      # commit_message: # optional
      # Set a custom full commit message without a triggered commit hash
      # full_commit_message: # optional
      # Set tag name
      # tag_name: # optional
      # Set tag message
      # tag_message: # optional
      # Enable the GitHub Pages built-in Jekyll
      # enable_jekyll: # optional, default is false
      # An alias for enable_jekyll to disable adding .nojekyll file to master or gh-pages branches
      # disable_nojekyll: # optional, default is false
      # Set custom domain
      # cname: # optional
      # Set files or directories to exclude from a publish directory.
      # exclude_assets: # optional, default is .github
